auth0/auth0-authorization-extension

client/components/Configuration/RuleSettingsForm.jsx, client/components/Logs/LogDialog.jsx, client/containers/ConfigurationRule.jsx, client/containers/Permissions.js, client/utils/connectContainer.js, client/utils/index.js, server/views/index.js
typo
empty components are self closing
remove connectContainer
styleguide update (from 4.8.8 to 4.8.10)
=> minimal fixes

index.js, package.json, server/init.js, webtask.js
=> Config fix

server/plugins/html.js
=> Deep linking

server/api/configuration/routes/get_configuration_status.js, server/lib/storage/database.js
size and type of database were added to GET /api/configuration/status response
=> Database size

build/extension/webpack.config.js, build/webpack/config.base.js, client/actions/configuration.js, client/components/Configuration/RuleStatus.jsx, client/containers/App.jsx
- show warning if size is higher than 500 (configurable)
- goToImportExport() will need to be fixed once it's **import-export** is moved to configuration
=> show database size warning

package.json
- bug fixed in extension-ui. we need to bump its version or add this line
=> You cannot edit permissions when adding/updating a Role

client/actions/groupNested.js, client/components/Groups/GroupPickerDialog.jsx, client/components/Groups/GroupRowPicker.jsx, client/components/Groups/GroupsTablePicker.jsx, client/containers/Group.jsx
- add nested fixed
- remove nested fixed
=> Nested fix

client/components/Groups/GroupForm.jsx
Edit Group should show a "Save" button
=> Edit Group should show a Save button

client/actions/groupMember.js, client/containers/User.jsx, server/api/configuration/routes/delete_apiaccess.js, server/api/configuration/routes/patch_apiaccess.js, server/api/configuration/routes/post_import.js, server/api/users-groups/routes/patch_user_add_to_group.js, server/plugins/routes.js
- remove group member fixed
- added user to group fixed
=> Group management from user details

server/api/groups-roles/routes/delete_roles.js, server/api/groups-roles/routes/get_nested_roles.js, server/api/groups-roles/routes/get_roles.js, server/api/groups-roles/routes/patch_roles.js, server/lib/queries.js, server/plugins/routes.js
added new endpoints:
- GET /api/groups/{id}/roles
- GET /api/groups/{id}/roles/nested
- PATCH /api/groups/{id}/roles
- DELETE /api/groups/{id}/roles
=> Group roles

client/actions/group.js, client/actions/permission.js, client/actions/role.js, client/actions/user.js, client/components/Groups/GroupsOverview.jsx, client/components/Permissions/PermissionsOverview.jsx, client/components/Roles/RolesOverview.jsx, client/components/Users/UserOverview.jsx, client/containers/Groups.jsx, client/containers/Permissions.js, client/containers/Roles.js, client/containers/Users.jsx, server/api/groups/routes/get_groups.js, server/api/permissions/routes/get_permissions.js, server/api/roles/routes/get_roles.js, server/api/users/routes/get_users.js
Users search
Groups searchbar and GroupsOverview
Roles searchbar and RolesOverview
Permission searchbar and RolesOverview
fix groups, permissions, roles and users w/ new syntax to search
=> searchbar implementation

client/actions/groupMember.js, client/actions/userPicker.js, client/components/Groups/GroupMembers.jsx, client/components/Groups/GroupMembersDialog.jsx, client/components/Groups/GroupsOverview.jsx, client/components/Users/UserPickerDialog.jsx, client/containers/Group.jsx, client/containers/Groups.jsx, client/reducers/group.js
Missing:
- delete members
- pagination
=> Add members

client/components/Groups/GroupMemberRemoveAction.jsx, client/components/Groups/GroupMembersDialog.jsx, client/components/Users/UsersTable.jsx, client/containers/Group.jsx
=> Remove user from group

client/components/Configuration/APIAccessTab.jsx, client/utils/createForm.js, server/api/configuration/routes/get_apiaccess.js
Fixed on extension-ui too (https://github.com/auth0-extensions/auth0-extension-ui/commit/e1ac8e458ad9cb44d840c1bdf377c42e418c4cbb)
=> fix configuration initialvalues

build/extension/webpack.config.js, build/webpack/config.base.js, client/actions/group.js, client/actions/groupMember.js, client/actions/user.js, client/components/Groups/GroupMembers.jsx, client/components/Users/UserOverview.jsx, client/containers/Group.jsx, client/containers/Users.jsx, client/reducers/users.js, server/api/users/routes/get_users.js, server/lib/users.js
Add pagination to lists of users
- both in Users and Groups
- 5 users per page
Note: It does not solve multi select issues.
=> Add pagination

server/lib/storage/database.js, server/plugins/html.js, tests/server/permissions-route.tests.js, tests/server/roles-route.tests.js
Deny user to delete roles or permissions if they are linked to any other records.
=> Check roles and permissions before delete

build/extension/webpack.config.js, build/webpack/config.base.js, client/actions/user.js, client/components/Groups/GroupMembersDialog.jsx, client/components/Groups/GroupsOverview.jsx, client/components/Users/UserPickerDialog.jsx, client/containers/Group.jsx
DO NOT MERGE YET.
TODO: decide how we should handle this..
The current version (with these comments) basically fetches data from server every 250 ms (MULTISELECT_DEBOUNCE_MS). However we can have an improvement for some users that have less that MAX_MULTISELECT_USERS to not fetch it from server every time. I did not add this right now because I'm not sure if it's what auth0 wants and also this.props.totalUsers is being changed overtime due to reducer multiple uses. @sandrinodimattia what do you think about these considerations?
=> multiselect issues

client/components/Groups/GroupMembers.jsx
Group Details has 'MEMBERS OF THIS GROUP' and 'ALL MEMBERS' buttons - this PR implements switch operation taking into account what is selected
=> show content based on tab selection

client/actions/groupMember.js, client/components/Groups/GroupsOverview.jsx, client/containers/Group.jsx
add members to groups is done using userId and not email
=> add memebers based on userid

server/lib/storage/database.js
only allows to delete a group if it's not nested by another groups
=> Should not allow to delete group if it linked to another record

tests/client/reducers/configuration.tests.js, tests/client/reducers/group.tests.js, tests/client/reducers/groupRoles.tests.js, tests/client/reducers/user.tests.js, tests/client/reducers/userRoles.tests.js
fixing FE tests
Added some more that were not in place
=> Fix FE tests

server/api/configuration/schemas/storage.js, server/api/users-groups/routes/patch_user_add_to_group.js, server/api/users-roles/routes/delete_user_remove_from_roles.js, server/api/users-roles/routes/patch_user_add_to_roles.js
because mapSeries was added in v3, and webtask has only bluebird@2.9.26
=> mapSeries replaced by each

Dockerfile
Fix a missing "\\"
Correct the npm run script command.
=> Fix Dockerfile.

client/components/Roles/RoleDialog.jsx
init first application as salected
=> next button enabled

client/reducers/group.js, tests/client/reducers/group.tests.js
- Loading for adding roles is AddRoles (should I change this name?)
=> After adding roles to a group, the page jumps back to group members

.gitignore, scripts/authz-api.js, scripts/script-settings.example.json
This PR does not affect any functionality of the extension. Simply added script for load testing.
=> Added script for load testing

CHANGELOG.md
Update the changelog with all changes up to current (2.5.0)
=> Update changelog to 2.5.0

CHANGELOG.md, build/webpack/config.base.js, build/webpack/config.dev.js, server/plugins/html.js, server/views/index.js
IE11 doesn't want to work with `axios`. Adding `babel-polyfill` seems to solve that issue. 
Slack: https://auth0.slack.com/archives/C9170558S/p1542872905163500
Jira: https://auth0team.atlassian.net/browse/KEY-603
✅This change has been tested locally (both IE11 and Chrome)
✅ This can be deployed any time
=> KEY-603: IE11 support

CHANGELOG.md
Add one more migration step for versions <2.6 
N/A
https://auth0.slack.com/archives/CB9UESQ4F/p1581331218145500 (internal only)
🚫 This change has been tested in a Webtask
🚫 This change has unit test coverage
🚫 This change has integration test coverage
🚫 This change has been tested for performance
N/A we don't need to deploy, docs only
N/A
N/A
N/A
✅
=> Add one more migration step for versions <2.6

.circleci/config.yml
Avoid parallel execution to resolve issues with `npm ci` and rate limits.
If there were visual changes to the application with this change, please include before and after screenshots here. If it has animation, please use screen capture software like  to make a gif.
https://auth0team.atlassian.net/browse/AUTHZ-2165
Tested in circle cI.
✅  This can be deployed any time
In order to verify that the deployment was successful we will check circle CI.
We will rollback if there is any error or outage.
Revert the PR.
✅
=> [AUTHZ-2165] Run CI workflows in series

package.json, tests/integration/group.tests.js
Fix the groups functional tests.
N/A
https://auth0team.atlassian.net/browse/AUTHZ-2163
In fact, the whole PR is tests.
✅ This can be deployed any time
In order to verify that the deployment was successful we will check Circle ci.
We will rollback if there is any error or outage.
Revert the PR.
✅
=> [AUTHZ-2163] Fix groups functional tests

server/lib/queries.js
=> Fix linter

CHANGELOG.md, package-lock.json, package.json, webtask.json
=> Minor version bump

CHANGELOG.md, package-lock.json, package.json, server/api/users/routes/get_users.js, webtask.json
Adds user search option (defaults to v3) for performance improvements.
https://auth0team.atlassian.net/browse/AUTHZ-2198
try changing the selected user search engine, v2 will fail on public cloud as it has been deprecated.
🚫 This change has been tested in a Webtask
🚫 This change has unit test coverage
🚫 This change has integration test coverage
🚫 This change has been tested for performance
Needs to be deployed manually currently to S3.
✅This can be deployed any time
Manual testing will be required
We will rollback if user search is no longer functional.
There is no roll back in this deployment, as it will be preview prior to release.
✅
=> add user search configuration option

README.md
Update readme to reflect support for node 12
=> Update README.md to reflect node 12 support

README.md, gulpfile.js, package-lock.json, package.json
Use Argo Tunnel instead of ngrok
N/A
https://auth0team.atlassian.net/browse/AUTHZ-2608
When you follow the instructions of README, the local development environment & local production mode works.
🚫 This change has been tested in a Webtask
🚫 This change has unit test coverage
🚫 This change has integration test coverage
🚫 This change has been tested for performance
✅ This can be deployed any time
N/A
We will rollback if we experience errors
Unpublish this version
All good
=> AUTHZ-2608 - Use Argo Tunnel instead of ngrok

README.md
Remove line from README about adding user groups in the future.
N/A
@hous asked for this
N/A
✅🚫 This change has been tested in a Webtask
✅🚫 This change has unit test coverage
✅🚫 This change has integration test coverage
✅🚫 This change has been tested for performance
N/A
✅🚫 This can be deployed any time
N/A
N/A
N/A
N/A
=> Update README: remove user groups plans
